baseURL = "http://hamzahch.com/"
languageCode = "en-us"
title = "Hamzah Chaudhry"
theme = "manzil"
copyright = "Â© 2020 Hamzah Chaudhry"
googleAnalytics = "UA-166782089-1"
paginate = 4
summaryLength = 40

[params]
    logo = "hamzah chaudhry"
    description = "Student at UNC-Chapel Hill studying Computer Science and minoring in Entrepreneurship and Statistics"
    author = "Hamzah Chaudhry"

[[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = -4

[[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = -3

[[menu.main]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/hamzah-ch"
    weight = -2

[[menu.main]]
    name = "github"
    url = "https://github.com/hybrezz54"
    weight = -1